# Generated by Django 4.1 on 2022-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=120)),
                ('button', models.CharField(max_length=120)),
                ('background', models.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
