# Generated by Django 4.1 on 2022-08-15 18:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.ImageField(upload_to='about-icons')),
                ('image', models.ImageField(upload_to='about-images')),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='background',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=120)),
                ('tabs', models.ManyToManyField(to='homepage.abouttab')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
