# Generated by Django 4.1 on 2022-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_contactcard_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cards',
            field=models.ManyToManyField(to='homepage.contactcard'),
        ),
    ]
