# Generated by Django 4.1 on 2022-08-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_contact_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='background',
            new_name='image',
        ),
    ]
