# Generated by Django 4.1 on 2022-08-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_background_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='image',
            new_name='background',
        ),
    ]
