# Generated by Django 4.1 on 2022-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_body_alter_message_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
