# Generated by Django 4.1 on 2022-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='project.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
