# Generated by Django 4.1 on 2022-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
