# Generated by Django 4.1 on 2022-08-18 15:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='info',
            field=tinymce.models.HTMLField(),
        ),
    ]
