# Generated by Django 4.1 on 2022-08-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_alter_footer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
